#!/bin/bash
# chrome-devtools-manager: Manage Chrome DevTools MCP across multiple projects
# Launches isolated Chrome instances, manages port assignments, detects conflicts
#
# Usage:
#   chrome-devtools-manager              Launch Chrome for current project
#   chrome-devtools-manager --list       Show port registry
#   chrome-devtools-manager --scan       Rescan all projects and update registry
#   chrome-devtools-manager --add [port] Add chrome-devtools to current project's .mcp.json
#   chrome-devtools-manager --path <dir> Add a search path (e.g. ~/Projects/*)
#   chrome-devtools-manager --help       Show help
#
# Config: ~/.chrome-devtools-manager
# Chrome DevTools MCP: https://github.com/ChromeDevTools/chrome-devtools-mcp

REGISTRY="$HOME/.chrome-devtools-manager"
CMD_NAME="chrome-devtools-manager"
DEFAULT_PATHS=(
  "~/Herd/*"
  "~/Herd/*/*"
  "~/Code/*"
  "~/Code/*/*"
)

# --- Config file management ---

init_config() {
  if [ ! -f "$REGISTRY" ]; then
    echo "# Chrome DevTools MCP Port Registry" > "$REGISTRY"
    echo "# https://github.com/ChromeDevTools/chrome-devtools-mcp" >> "$REGISTRY"
    echo "#" >> "$REGISTRY"
    echo "# SEARCH PATHS (add your project directories here)" >> "$REGISTRY"
    for p in "${DEFAULT_PATHS[@]}"; do
      echo "$p" >> "$REGISTRY"
    done
    echo "#" >> "$REGISTRY"
    echo "# REGISTRY (auto-generated by $CMD_NAME --scan)" >> "$REGISTRY"
    echo "# Last scanned: never" >> "$REGISTRY"
    echo "# PROJECT|PORT|PATH" >> "$REGISTRY"
  fi
}

get_search_paths() {
  local in_paths=false
  local paths=()

  while IFS= read -r line; do
    [ -z "$line" ] && continue

    if echo "$line" | grep -q "^# SEARCH PATHS"; then
      in_paths=true
      continue
    fi
    if echo "$line" | grep -q "^# REGISTRY"; then
      break
    fi

    if $in_paths; then
      if echo "$line" | grep -q "^#"; then
        continue
      fi
      paths+=("$line")
    fi
  done < "$REGISTRY"

  if [ ${#paths[@]} -eq 0 ]; then
    for p in "${DEFAULT_PATHS[@]}"; do
      paths+=("$p")
    done
  fi

  echo "${paths[@]}"
}

# --- Chrome path detection ---

get_chrome_path() {
  local os=$(uname -s)

  case "$os" in
    Darwin)
      echo "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
      ;;
    Linux)
      if grep -qi microsoft /proc/version 2>/dev/null; then
        # WSL2: use Windows Chrome
        echo "/mnt/c/Program Files/Google/Chrome/Application/chrome.exe"
      elif command -v google-chrome &>/dev/null; then
        echo "google-chrome"
      elif command -v google-chrome-stable &>/dev/null; then
        echo "google-chrome-stable"
      elif command -v chromium-browser &>/dev/null; then
        echo "chromium-browser"
      elif command -v chromium &>/dev/null; then
        echo "chromium"
      else
        echo ""
      fi
      ;;
    *)
      echo ""
      ;;
  esac
}

# --- Launch Chrome ---

launch_chrome() {
  local project_name=$(basename "$PWD")
  local port=$(grep -o '127\.0\.0\.1:[0-9]*' .mcp.json 2>/dev/null | head -1 | cut -d: -f2)

  if [ -z "$port" ]; then
    echo "No chrome-devtools port found in .mcp.json"
    echo ""
    echo "Add chrome-devtools to this project:"
    echo "  $CMD_NAME --add"
    return 1
  fi

  local chrome_path=$(get_chrome_path)

  if [ -z "$chrome_path" ]; then
    echo "Error: Could not find Chrome/Chromium installation"
    echo ""
    echo "Supported locations:"
    echo "  macOS:  /Applications/Google Chrome.app"
    echo "  Linux:  google-chrome, chromium-browser, or chromium"
    echo "  WSL2:   /mnt/c/Program Files/Google/Chrome/Application/chrome.exe"
    return 1
  fi

  echo "Launching Chrome for '$project_name' on port $port..."
  "$chrome_path" \
    --remote-debugging-port="$port" \
    --user-data-dir="/tmp/chrome-$project_name" 2>/dev/null &
}

# --- Scanning ---

scan_projects() {
  local tmp=$(mktemp)
  local search_paths=($(get_search_paths))

  echo "Scanning for Chrome DevTools MCP configurations..."
  for pattern in "${search_paths[@]}"; do
    echo "  $pattern"
  done
  echo ""

  for pattern in "${search_paths[@]}"; do
    local expanded=$(echo "$pattern" | sed "s|^~|$HOME|")
    for file in $expanded/.mcp.json; do
      [ -f "$file" ] || continue
      local port=$(grep -o '127\.0\.0\.1:[0-9]*' "$file" 2>/dev/null | head -1 | cut -d: -f2)
      [ -z "$port" ] && continue
      local project_dir=$(dirname "$file")
      local project_name=$(basename "$project_dir")
      local short_path=$(echo "$project_dir" | sed "s|$HOME|~|")
      echo "$project_name|$port|$short_path" >> "$tmp"
    done
  done

  sort -t'|' -k2 -n "$tmp" | uniq > "$REGISTRY.tmp"

  local new_registry=$(mktemp)
  echo "# Chrome DevTools MCP Port Registry" > "$new_registry"
  echo "# https://github.com/ChromeDevTools/chrome-devtools-mcp" >> "$new_registry"
  echo "#" >> "$new_registry"
  echo "# SEARCH PATHS (add your project directories here)" >> "$new_registry"

  for pattern in "${search_paths[@]}"; do
    echo "$pattern" >> "$new_registry"
  done

  echo "#" >> "$new_registry"
  echo "# REGISTRY (auto-generated by $CMD_NAME --scan)" >> "$new_registry"
  echo "# Last scanned: $(date '+%Y-%m-%d %H:%M:%S')" >> "$new_registry"
  echo "# PROJECT|PORT|PATH" >> "$new_registry"
  cat "$REGISTRY.tmp" >> "$new_registry"

  mv "$new_registry" "$REGISTRY"
  rm -f "$tmp" "$REGISTRY.tmp"
}

# --- Display ---

get_entries() {
  grep -v "^#" "$REGISTRY" | grep -v "^$" | grep "|"
}

get_max_port() {
  local entries="$1"
  local max_port=9221

  if [ -n "$entries" ]; then
    while IFS='|' read -r name port path; do
      [ "$port" -gt "$max_port" ] 2>/dev/null && max_port=$port
    done <<< "$entries"
  fi

  echo "$max_port"
}

show_registry() {
  if [ ! -f "$REGISTRY" ]; then
    echo "No registry found. Run: $CMD_NAME --scan"
    return 1
  fi

  local timestamp=$(grep "^# Last scanned:" "$REGISTRY" | sed 's/^# Last scanned: //')
  local entries=$(get_entries)

  if [ -z "$entries" ]; then
    echo ""
    echo "No projects with Chrome DevTools MCP found."
    echo "Last scanned: $timestamp"
    echo ""
    echo "To add chrome-devtools to the current project: $CMD_NAME --add"
    return 0
  fi

  local max_port=$(get_max_port "$entries")

  echo ""
  echo "Chrome DevTools MCP Port Registry"
  echo "==================================="
  printf "%-30s %-8s %s\n" "PROJECT" "PORT" "PATH"
  printf "%-30s %-8s %s\n" "-------" "----" "----"

  while IFS='|' read -r name port path; do
    printf "%-30s %-8s %s\n" "$name" "$port" "$path"
  done <<< "$entries"

  local conflicts=$(echo "$entries" | cut -d'|' -f2 | sort | uniq -d)
  if [ -n "$conflicts" ]; then
    echo ""
    for dup_port in $conflicts; do
      local projects=$(echo "$entries" | grep "|$dup_port|" | cut -d'|' -f1 | tr '\n' ', ' | sed 's/,$//')
      echo "!! CONFLICT: $projects both use port $dup_port"
    done
  fi

  echo ""
  echo "Last scanned: $timestamp"
  echo "Next available port: $((max_port + 1))"
  echo ""
}

# --- Add chrome-devtools to current project ---

add_to_project() {
  local requested_port="$1"

  if ! command -v jq &>/dev/null; then
    echo "Error: jq is required for --add"
    echo ""
    echo "Install it:"
    echo "  macOS:         brew install jq"
    echo "  Ubuntu/Debian: sudo apt install jq"
    echo "  Fedora/RHEL:   sudo dnf install jq"
    return 1
  fi

  local port="$requested_port"
  if [ -z "$port" ]; then
    init_config
    local entries=$(get_entries)
    local max_port=$(get_max_port "$entries")
    port=$((max_port + 1))
  fi

  if ! [[ "$port" =~ ^[0-9]+$ ]]; then
    echo "Error: Invalid port '$port'"
    return 1
  fi

  if [ -f "$REGISTRY" ]; then
    local conflict=$(get_entries | grep "|$port|")
    if [ -n "$conflict" ]; then
      local conflict_name=$(echo "$conflict" | cut -d'|' -f1)
      echo "Error: Port $port is already used by '$conflict_name'"
      echo "Run '$CMD_NAME --list' to see all assignments"
      return 1
    fi
  fi

  local project_name=$(basename "$PWD")
  local mcp_file=".mcp.json"

  if [ -f "$mcp_file" ]; then
    if jq -e '.mcpServers["chrome-devtools"]' "$mcp_file" &>/dev/null; then
      echo "chrome-devtools already configured in $mcp_file"
      local existing_port=$(grep -o '127\.0\.0\.1:[0-9]*' "$mcp_file" | head -1 | cut -d: -f2)
      echo "Current port: $existing_port"
      return 1
    fi

    local tmp=$(mktemp)
    jq --arg port "$port" '.mcpServers["chrome-devtools"] = {
      "command": "npx",
      "args": ["-y", "chrome-devtools-mcp@latest", "--browserUrl", ("http://127.0.0.1:" + $port)]
    }' "$mcp_file" > "$tmp" && mv "$tmp" "$mcp_file"
  else
    jq -n --arg port "$port" '{
      mcpServers: {
        "chrome-devtools": {
          command: "npx",
          args: ["-y", "chrome-devtools-mcp@latest", "--browserUrl", ("http://127.0.0.1:" + $port)]
        }
      }
    }' > "$mcp_file"
  fi

  echo "Added chrome-devtools to $project_name on port $port"
  echo "File: $(pwd)/$mcp_file"
  echo ""
  echo "Launch Chrome with: $CMD_NAME"
  echo ""

  scan_projects
  show_registry
  echo "Registry saved to ~/.chrome-devtools-manager"
}

# --- Add search path ---

add_path() {
  local new_path="$1"

  if [ -z "$new_path" ]; then
    echo "Error: No path provided"
    echo "Usage: $CMD_NAME --path ~/Projects/*"
    return 1
  fi

  init_config

  if grep -qF "$new_path" "$REGISTRY" 2>/dev/null; then
    echo "Path already registered: $new_path"
    return 0
  fi

  local current_paths=($(get_search_paths))
  current_paths+=("$new_path")

  echo "# Chrome DevTools MCP Port Registry" > "$REGISTRY"
  echo "# https://github.com/ChromeDevTools/chrome-devtools-mcp" >> "$REGISTRY"
  echo "#" >> "$REGISTRY"
  echo "# SEARCH PATHS (add your project directories here)" >> "$REGISTRY"
  for p in "${current_paths[@]}"; do
    echo "$p" >> "$REGISTRY"
  done
  echo "#" >> "$REGISTRY"
  echo "# REGISTRY (auto-generated by $CMD_NAME --scan)" >> "$REGISTRY"
  echo "# Last scanned: never" >> "$REGISTRY"
  echo "# PROJECT|PORT|PATH" >> "$REGISTRY"

  echo "Added search path: $new_path"
  echo ""

  scan_projects
  show_registry
  echo "Registry saved to ~/.chrome-devtools-manager"
}

# --- Help ---

show_help() {
  echo "$CMD_NAME: Manage Chrome DevTools MCP across multiple projects"
  echo ""
  echo "Usage:"
  echo "  $CMD_NAME              Launch Chrome for current project"
  echo "  $CMD_NAME --list       Show port registry"
  echo "  $CMD_NAME --scan       Rescan all projects and update registry"
  echo "  $CMD_NAME --add [port] Add chrome-devtools to current project"
  echo "  $CMD_NAME --path <dir> Add a search path (e.g. ~/Projects/*)"
  echo "  $CMD_NAME --help       Show this help"
  echo ""
  echo "Config file: ~/.chrome-devtools-manager"
  echo ""
  echo "Getting started:"
  echo "  1. $CMD_NAME --scan              Scan for existing projects"
  echo "  2. cd ~/my-project"
  echo "  3. $CMD_NAME --add               Add chrome-devtools (auto-assigns port)"
  echo "  4. $CMD_NAME                     Launch Chrome for this project"
  echo ""
  echo "Adding custom search paths:"
  echo "  $CMD_NAME --path ~/Projects/*    Single level"
  echo "  $CMD_NAME --path ~/Work/*/*      Nested (org/project)"
  echo ""
  echo "Shell function for .zshrc/.bashrc:"
  echo "  chrome-debug() { $CMD_NAME; }    Quick alias"
  echo ""
  echo "Requires: jq (for --add only). Install: brew install jq"
  echo "Chrome DevTools MCP: https://github.com/ChromeDevTools/chrome-devtools-mcp"
}

# --- Main ---

init_config

case "$1" in
  --list|-l)
    show_registry
    ;;
  --scan)
    scan_projects
    show_registry
    echo "Registry saved to ~/.chrome-devtools-manager"
    ;;
  --add)
    add_to_project "$2"
    ;;
  --path)
    add_path "$2"
    ;;
  --help|-h)
    show_help
    ;;
  "")
    launch_chrome
    ;;
  *)
    echo "Unknown option: $1"
    echo ""
    show_help
    ;;
esac
